PREFIX p: <http://sedrinks.com>
PREFIX d: <http://sedrinks.com/ns/data#>

    SELECT ?Minuman ?JenisMinuman ?Pemanis ?Pengawet ?Usia ?Tersedia 
    WHERE
    { 
        ?s  d:namaMinuman ?Minuman ;
            d:jenisMinuman ?jenisMinuman;
            d:Pemanis ?Pemanis;
            d:Pengawet ?Pengawet;
            d:Usia ?Usia;
            d:Tersedia ?Tersedia;
            

    }
